name: Deploy infrastructure

on:
  push:
    branches:
      - dev
      - test
      - main
    paths:
      - "infrastructure/**"
  workflow_dispatch:
    inputs:
      deploy_to_dev:
        description: "Deploy to DEV?"
        required: true
        default: "true"

env:
  PROJECT_NAME: trieste
  RG_LOCATION: westeurope

defaults:
  run:
    working-directory: infrastructure

jobs:
  deploy-dev:
    uses: Neoteroi/BlackSheep-Azure-API/.github/workflows/infrastructure-env.yml@main
    with:
      PROJECT_NAME: ${{ env.PROJECT_NAME }}
      ENV_NAME: dev
      AZURE_SUBSCRIPTION: ${{ secrets.DEV_AZURE_SUBSCRIPTION }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.DEV_AZURE_CREDENTIALS }}
      DBSA_PASSWORD: ${{ secrets.DEV_DBSA_PASSWORD }}

  deploy-test:
    uses: Neoteroi/BlackSheep-Azure-API/.github/workflows/infrastructure-env.yml@main
    with:
      PROJECT_NAME: ${{ env.PROJECT_NAME }}
      ENV_NAME: test
      AZURE_SUBSCRIPTION: ${{ secrets.DEV_AZURE_SUBSCRIPTION }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.TEST_AZURE_CREDENTIALS }}
      DBSA_PASSWORD: ${{ secrets.TEST_DBSA_PASSWORD }}
